name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the Node.js version that matches your project

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/kafia-home-page  # Path to the build output directory
        user_name: 'GitHub Actions'
        user_email: 'actions@github.com'
